[package]
name = "cure_web"
version = "0.1.0"
edition = "2021"



[dependencies]
cure_asn1 = {path="../cure_asn1/"}
serde = { version = "1.0.*", default-features = false }
serde_json="1.0"
wasm-bindgen = "0.2.100"
chrono = "0.4.23"
regex = "1"

